### ISSUE TITLE
Wallet in loop on authentication screen

### ISSUE THREAD

**Issue by GreggyGB** [navcoin/WhisperWallet#80]
When accessing wallet on Android 9 with pin authentication wallet keeps asking for pin number and gets stuck in a loop

**Comment by aguycalled** [comment]
Hi, could you try downloading the apk again? it should now work in all the cases unless there is not even a pin code set.

**Comment by GreggyGB** [comment]
https://user-images.githubusercontent.com/43723411/163684769-7a6aac9b-2199-4481-b210-3b8390a9ed9a.mp4

I downloaded apk again and loop still occurs. I am using Samsung s8 SM-G950F for this test

**Comment by aguycalled** [comment]
I understand the unlock code you are introducing is the same you use to unlock your phone :?

**Comment by GreggyGB** [comment]
Yes. For testing purpose I put in incorrect pin and I got another message so that part works fine. When typing correct pin it is creating that loop.

**Comment by aguycalled** [comment]
Should be solved in #96

**Comment by tsejerome** [comment]
I believe this is not resolved as I encountered https://github.com/navcoin/WhisperWallet/issues/135

**Comment by tsejerome** [comment]
Will take over this

**Comment by tsejerome** [comment]
Resolved in main ytd
